name: duzzle-dev

services:
  dev:
    build:
      context: .
    volumes:
      - ./:/app:cached
    ports:
      - "9000:9000"
      - "9003:9003"
    command: tail -f /dev/null
    environment:
      PHP_CS_FIXER_IGNORE_ENV: 1
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: >
        client_host=host.docker.internal
        client_port=9003
        start_with_request=yes

  wiremock:
    image: wiremock/wiremock
    ports:
      - "8080:8080"
    environment:
      WIREMOCK_OPTIONS: "--verbose --global-response-templating --disable-gzip"
    volumes:
      - ./tests/__support/wiremock:/home/wiremock:ro

  json-server:
    image: clue/json-server
    ports:
      - "8081:80"
    volumes:
      - ./tests/__support/json-server/db.json:/data/db.json
