name: Quality

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.3'
#          tools: composer:v2
#          coverage: none
#
#      - name: Download dependencies
#        run: composer install --no-interaction --no-progress
#
#      - name: Download PHPStan
#        run: composer bin phpstan update --no-interaction --no-progress
#
#      - name: Execute PHPStan
#        run: vendor/bin/phpstan analyze --no-progress
#
#  php-cs-fixer:
#    name: PHP-CS-Fixer
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.3'
#          tools: composer:v2
#          coverage: none
#
#      - name: Download dependencies
#        run: composer install --no-interaction --no-progress
#
#      - name: Download PHP CS Fixer
#        run: composer bin php-cs-fixer update --no-interaction --no-progress
#
#      - name: Execute PHP CS Fixer
#        run: vendor/bin/php-cs-fixer fix --diff --dry-run
#
#  unit-tests:
#    name: Unit Tests
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.3'
#          tools: composer:v2
#          coverage: none
#
#      - name: Download dependencies
#        run: composer install --no-interaction --no-progress
#
#      - name: Download Pest
#        run: composer bin pest update --no-interaction --no-progress
#
#      - name: Run Tests
#        run: vendor/bin/pest tests/Unit/
#
#  arch-tests:
#    name: Architecture Tests
#    runs-on: ubuntu-22.04
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: '8.3'
#          tools: composer:v2
#          coverage: none
#
#      - name: Download dependencies
#        run: composer install --no-interaction --no-progress
#
#      - name: Download Pest
#        run: composer bin pest update --no-interaction --no-progress
#
#      - name: Run Tests
#        run: vendor/bin/pest tests/Architecture/

  tests:
    runs-on: ubuntu-latest

    env:
      WIREMOCK_HOST: http://localhost:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      - name: Start WireMock container
        run: |
          docker run -d \
            --name wiremock \
            -p 8080:8080 \
            wiremock/wiremock:latest \
            -v "$PWD/tests/__support/wiremock":/home/wiremock

      - name: Wait for WireMock
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8080/__admin >/dev/null 2>&1; then
              echo "WireMock is up!"
              break
            fi
            echo "Waiting for WireMock..."
            sleep 2
          done

      - name: Run Pest tests
        run: |
          vendor/bin/pest --coverage

#      # 7) (Optional) Upload coverage artifacts
#      - name: Upload coverage artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: coverage-report
#          path: coverage/
